### ISSUE TITLE
Issue w/MODA 250-m processing

### ISSUE THREAD

**Issue by dotis** [USF-IMARS/l2-processing#8]
MODIS GEO files are not being created properly.

"modis_GEO.py" is failing, causing the rest of the processing to fail.

From logs:
"Percent valid data (0.00) is less than threshold (95.00)
ERROR: MODIS geolocation processing failed."

I think the issue is related to this recent post and others in the thread:

https://forum.earthdata.nasa.gov/viewtopic.php?t=3378&start=10#p15846

They say to run the modis_atteph routine, but I'm not sure where we would need to run that. Any ideas?

All ROI (Belize, TB, USVI) start to fail on day 2020335, which indicates that the issue with the altitude files affects dates after that and affects all processing. The old files work, but not the recent ones.

**Comment by 7yl4r** [comment]
I think the script ran as it should on manglillo using both the root account and your account:

```
(base) root@manglilloo:~/l2gen_tests# bash /srv/imars-objects/homes/dotis/TB_MODA_250/process_image_BEL_MODA_250m.sh A2020335185000
(base) root@manglilloo:~/l2gen_tests# bash /srv/imars-objects/homes/dotis/TB_MODA_250/process_image_BEL_MODA_250m.sh A2020335185000
unzipping...
running modis_GEO...
MODIS GEO version 6.1.0, built Aug 16 2019 12:46:24
scan: 0 out of 29 Thu Jul 20 16:47:47 2023
scan: 10 out of 29 Thu Jul 20 16:47:48 2023
scan: 20 out of 29 Thu Jul 20 16:47:48 2023
running modis_L1B
MODIS Aqua L1B version 6.2.1_obpg, built Aug 16 2019 12:46:19
scan: 0 out of 29 Thu Jul 20 16:47:51 2023
scan: 10 out of 29 Thu Jul 20 16:47:51 2023
scan: 20 out of 29 Thu Jul 20 16:47:52 2023
running l2gen...
Input file /srv/imars-objects/tpa_pgs/belize/l1b/A2020335185000.L1B_LAC is MODIS Aqua Level-1B HDF-EOS product.
Loading default parameters from /opt/ocssw/share/common/msl12_defaults.par
Loading default parameters for MODISA from /opt/ocssw/share/modis/msl12_defaults.par
[...]
Processing Completed
zipping result...
cleaning up...
```

```
manglilloo:~> bash /srv/imars-objects/homes/dotis/TB_MODA_250/process_image_BEL_MODA_250m.sh A2020335185000
unzipping...
running modis_GEO...
MODIS GEO version 6.1.0, built Aug 16 2019 12:46:24
scan: 0 out of 29 Thu Jul 20 16:51:29 2023
scan: 10 out of 29 Thu Jul 20 16:51:29 2023
scan: 20 out of 29 Thu Jul 20 16:51:30 2023
running modis_L1B
MODIS Aqua L1B version 6.2.1_obpg, built Aug 16 2019 12:46:19
scan: 0 out of 29 Thu Jul 20 16:51:32 2023
scan: 10 out of 29 Thu Jul 20 16:51:33 2023
scan: 20 out of 29 Thu Jul 20 16:51:33 2023
running l2gen...
```

on seashell I get errors:
```
seashell 114 :/home1/dotis> bash /srv/imars-objects/homes/dotis/TB_MODA_250/process_image_BEL_MODA_250m.sh A2020335185000
unzipping...
bzip2: Can't open input file /srv/imars-objects/tpa_pgs/belize/l1a_A/A2020335185000.L1A_LAC.x.hdf.bz2: No such file or directory.
running modis_GEO...
/opt/ocssw/opt/bin/hdp: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /opt/ocssw/opt/bin/../lib/libmfhdf.so.0)
/opt/ocssw/opt/bin/hdp: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /opt/ocssw/opt/bin/../lib/libdf.so.0)
/opt/ocssw/opt/bin/hdp: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /opt/ocssw/opt/bin/../lib/../lib/libxdr.so.0)
/opt/ocssw/opt/bin/hdp: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /opt/ocssw/opt/bin/../lib/../lib/libjpeg.so.9)
Error!  dump_metadata failed.
running modis_L1B
/opt/ocssw/opt/bin/hdp: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /opt/ocssw/opt/bin/../lib/libmfhdf.so.0)
/opt/ocssw/opt/bin/hdp: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /opt/ocssw/opt/bin/../lib/libdf.so.0)
/opt/ocssw/opt/bin/hdp: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /opt/ocssw/opt/bin/../lib/../lib/libxdr.so.0)
/opt/ocssw/opt/bin/hdp: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /opt/ocssw/opt/bin/../lib/../lib/libjpeg.so.9)
Error!  dump_metadata failed.
running l2gen...
l2gen: error while loading shared libraries: libquadmath.so.0: cannot open shared object file: No such file or directory
zipping result...
cleaning up...
```

**Comment by dotis** [comment]
Thanks. Try it with a file in 2021. I think 2020335 is the last day it works.
________________________________

**Comment by dotis** [comment]
I tried it with a 2021 file this morning and the GEO portion did not work.
________________________________

**Comment by 7yl4r** [comment]
I ran modis_atteph on a failing file:

```
(base) root@manglilloo:~/tmp-test# export OCSSWROOT=/opt/ocssw
(base) root@manglilloo:~/tmp-test# source $OCSSWROOT/OCSSW_bash.env
(base) root@manglilloo:~/tmp-test# /opt/ocssw/scripts/modis_atteph.py /srv/imars-objects/tpa_pgs/belize/l1a_A/A2021215195000.L1A_LAC.x.hdf 
Aqua
Aqua
att1=/opt/ocssw/var/anc/2021/215/PM1ATTNR.P2021215.1800.003
eph1=/opt/ocssw/var/anc/2021/215/PM1EPHND.P2021215.1200.003
```

Then tried re-running and got the same error.
The files from running `modis_atteph` exist and have permissions indicating that a previous run of yours created them:

```
(base) tylar@manglilloo:~$ ls -lah /opt/ocssw/var/anc/2021/215
total 5.8M
drwxrwxr-x   2 dotis imars-common 4.0K Mar 25 05:09 .
drwxrwxr-x 366 dotis imars-common  12K Apr  1 22:20 ..
-rw-rw-r--   1 dotis imars-common 452K Mar 25 05:09 PM1ATTNR.P2021215.1800.003
-rw-rw-r--   1 dotis imars-common 5.3M Mar 25 05:09 PM1EPHND.P2021215.1200.003
```

-----------------

I found [this known issue from the OBDAAC forum](https://oceancolor.gsfc.nasa.gov/forum/oceancolor/topic_show.pl?tid=12848) and followed the advice there. The file appears to be processing correctly now.

**Comment by dotis** [comment]
Does modis_atteph need to be run for each file? The previously created files look like they are from March. I'm not sure what I should change to press forward here. Should I add a line for atteph in my processing script?

**Comment by dotis** [comment]
Here is the script currently:

#!/bin/bash

# processes given image filename
# usage:        ./process_images.sh [filename]
# example:      ./process_images.sh A2011111103000

# give parameters useful names
FILENAME=$1  # eg A2011111103000

# set environment variabless
export OCSSWROOT=/opt/ocssw
source $OCSSWROOT/OCSSW_bash.env

DATA_DIR=/srv/imars-objects/tpa_pgs/belize

# script should exit immedidately if any command fails
# to change this comment out the following line or change to `set +e`
#set -e 

echo unzipping...
bzip2 -d $DATA_DIR/l1a_A/$FILENAME.L1A_LAC.x.hdf.bz2

echo running modis_GEO...
$OCSSWROOT/scripts/modis_GEO.py --output=$DATA_DIR/GEO/$FILENAME.GEO $DATA_DIR/l1a_A/$FILENAME.L1A_LAC.x.hdf

echo running modis_L1B
$OCSSWROOT/scripts/modis_L1B.py --okm=$DATA_DIR/l1b/$FILENAME.L1B_LAC --hkm=$DATA_DIR/l1b/$FILENAME.L1B_HKM --qkm=$DATA_DIR/l1b/$FILENAME.L1B_QKM $DATA_DIR/l1a_A/$FILENAME.L1A_LAC.x.hdf $DATA_DIR/GEO/$FILENAME.GEO

echo running l2gen...
l2gen ifile=$DATA_DIR/l1b/$FILENAME.L1B_LAC ofile=$DATA_DIR/L2_A250/$FILENAME.L2 geofile=$DATA_DIR/GEO/$FILENAME.GEO par=$DATA_DIR/BEL_MODA_l2gen_250m_v2.par

echo zipping result...
bzip2 -z $DATA_DIR/l1a_A/$FILENAME.L1A_LAC.x.hdf

echo cleaning up...
rm $DATA_DIR/l1b/$FILENAME*.L1B*
rm $DATA_DIR/GEO/$FILENAME*.GEO

**Comment by dotis** [comment]
All files seem to be processing. Big props to @7yl4r
